export interface CountryInfo {
  code: string;
  name: string;
  flag: string;
  isEligible: boolean;
  requiresSupportingDocs: boolean;
  supportedDocumentTypes?: string[];
}

export const COUNTRIES: CountryInfo[] = [
  // Official Turkish E-Visa eligible countries
  { code: "AFG", name: "Afghanistan", flag: "🇦🇫", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "DZA", name: "Algeria", flag: "🇩🇿", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "ATG", name: "Antigua and Barbuda", flag: "🇦🇬", isEligible: true, requiresSupportingDocs: false },
  { code: "ARM", name: "Armenia", flag: "🇦🇲", isEligible: true, requiresSupportingDocs: false },
  { code: "AUS", name: "Australia", flag: "🇦🇺", isEligible: true, requiresSupportingDocs: false },
  { code: "BHS", name: "Bahamas", flag: "🇧🇸", isEligible: true, requiresSupportingDocs: false },
  { code: "BGD", name: "Bangladesh", flag: "🇧🇩", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "BRB", name: "Barbados", flag: "🇧🇧", isEligible: true, requiresSupportingDocs: false },
  { code: "BMU", name: "Bermuda", flag: "🇧🇲", isEligible: true, requiresSupportingDocs: false },
  { code: "BTN", name: "Bhutan", flag: "🇧🇹", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "KHM", name: "Cambodia", flag: "🇰🇭", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "CAN", name: "Canada", flag: "🇨🇦", isEligible: true, requiresSupportingDocs: false },
  { code: "CPV", name: "Cape Verde", flag: "🇨🇻", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "CHN", name: "China", flag: "🇨🇳", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "invitation"] },
  { code: "HRV", name: "Croatia", flag: "🇭🇷", isEligible: true, requiresSupportingDocs: false },
  { code: "DMA", name: "Dominica", flag: "🇩🇲", isEligible: true, requiresSupportingDocs: false },
  { code: "DOM", name: "Dominican Republic", flag: "🇩🇴", isEligible: true, requiresSupportingDocs: false },
  { code: "TLS", name: "East Timor", flag: "🇹🇱", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "EGY", name: "Egypt", flag: "🇪🇬", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "GNQ", name: "Equatorial Guinea", flag: "🇬🇶", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "EST", name: "Estonia", flag: "🇪🇪", isEligible: true, requiresSupportingDocs: false },
  { code: "FJI", name: "Fiji", flag: "🇫🇯", isEligible: true, requiresSupportingDocs: false },
  { code: "CYP", name: "Cyprus", flag: "🇨🇾", isEligible: true, requiresSupportingDocs: false },
  { code: "GRD", name: "Grenada", flag: "🇬🇩", isEligible: true, requiresSupportingDocs: false },
  { code: "HTI", name: "Haiti", flag: "🇭🇹", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "HKG", name: "Hong Kong", flag: "🇭🇰", isEligible: true, requiresSupportingDocs: false },
  { code: "IND", name: "India", flag: "🇮🇳", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "IRQ", name: "Iraq", flag: "🇮🇶", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "JAM", name: "Jamaica", flag: "🇯🇲", isEligible: true, requiresSupportingDocs: false },
  { code: "LVA", name: "Latvia", flag: "🇱🇻", isEligible: true, requiresSupportingDocs: false },
  { code: "LBY", name: "Libya", flag: "🇱🇾", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "LTU", name: "Lithuania", flag: "🇱🇹", isEligible: true, requiresSupportingDocs: false },
  { code: "MDV", name: "Maldives", flag: "🇲🇻", isEligible: true, requiresSupportingDocs: false },
  { code: "MUS", name: "Mauritius", flag: "🇲🇺", isEligible: true, requiresSupportingDocs: false },
  { code: "MEX", name: "Mexico", flag: "🇲🇽", isEligible: true, requiresSupportingDocs: false },
  { code: "NAM", name: "Namibia", flag: "🇳🇦", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "NPL", name: "Nepal", flag: "🇳🇵", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "PAK", name: "Pakistan", flag: "🇵🇰", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "PSE", name: "Palestine", flag: "🇵🇸", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "PHL", name: "Philippines", flag: "🇵🇭", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "LCA", name: "Saint Lucia", flag: "🇱🇨", isEligible: true, requiresSupportingDocs: false },
  { code: "VCT", name: "Saint Vincent and the Grenadines", flag: "🇻🇨", isEligible: true, requiresSupportingDocs: false },
  { code: "SEN", name: "Senegal", flag: "🇸🇳", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "SLB", name: "Solomon Islands", flag: "🇸🇧", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "ZAF", name: "South Africa", flag: "🇿🇦", isEligible: true, requiresSupportingDocs: false },
  { code: "LKA", name: "Sri Lanka", flag: "🇱🇰", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "SUR", name: "Suriname", flag: "🇸🇷", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "TWN", name: "Taiwan", flag: "🇹🇼", isEligible: true, requiresSupportingDocs: false },
  { code: "VUT", name: "Vanuatu", flag: "🇻🇺", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "VNM", name: "Vietnam", flag: "🇻🇳", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "YEM", name: "Yemen", flag: "🇾🇪", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  
  // Additional E-visa eligible countries
  { code: "ITA", name: "Italy", flag: "🇮🇹", isEligible: true, requiresSupportingDocs: false },
  { code: "ESP", name: "Spain", flag: "🇪🇸", isEligible: true, requiresSupportingDocs: false },
  { code: "NLD", name: "Netherlands", flag: "🇳🇱", isEligible: true, requiresSupportingDocs: false },
  { code: "BRA", name: "Brazil", flag: "🇧🇷", isEligible: true, requiresSupportingDocs: false },
  { code: "IRN", name: "Iran", flag: "🇮🇷", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "KWT", name: "Kuwait", flag: "🇰🇼", isEligible: true, requiresSupportingDocs: false },
  { code: "OMN", name: "Oman", flag: "🇴🇲", isEligible: true, requiresSupportingDocs: false },
  { code: "QAT", name: "Qatar", flag: "🇶🇦", isEligible: true, requiresSupportingDocs: false },
  { code: "SAU", name: "Saudi Arabia", flag: "🇸🇦", isEligible: true, requiresSupportingDocs: false },
  { code: "ARE", name: "United Arab Emirates", flag: "🇦🇪", isEligible: true, requiresSupportingDocs: false },
  { code: "BHR", name: "Bahrain", flag: "🇧🇭", isEligible: true, requiresSupportingDocs: false },
  { code: "THA", name: "Thailand", flag: "🇹🇭", isEligible: true, requiresSupportingDocs: false },
  { code: "SGP", name: "Singapore", flag: "🇸🇬", isEligible: true, requiresSupportingDocs: false },
  { code: "MYS", name: "Malaysia", flag: "🇲🇾", isEligible: true, requiresSupportingDocs: false },
  { code: "IDN", name: "Indonesia", flag: "🇮🇩", isEligible: true, requiresSupportingDocs: false },
  { code: "KOR", name: "South Korea", flag: "🇰🇷", isEligible: true, requiresSupportingDocs: false },
  { code: "NOR", name: "Norway", flag: "🇳🇴", isEligible: true, requiresSupportingDocs: false },
  { code: "SWE", name: "Sweden", flag: "🇸🇪", isEligible: true, requiresSupportingDocs: false },
  { code: "DNK", name: "Denmark", flag: "🇩🇰", isEligible: true, requiresSupportingDocs: false },
  { code: "FIN", name: "Finland", flag: "🇫🇮", isEligible: true, requiresSupportingDocs: false },
  { code: "BEL", name: "Belgium", flag: "🇧🇪", isEligible: true, requiresSupportingDocs: false },
  { code: "AUT", name: "Austria", flag: "🇦🇹", isEligible: true, requiresSupportingDocs: false },
  { code: "CHE", name: "Switzerland", flag: "🇨🇭", isEligible: true, requiresSupportingDocs: false },
  { code: "PRT", name: "Portugal", flag: "🇵🇹", isEligible: true, requiresSupportingDocs: false },
  { code: "GRC", name: "Greece", flag: "🇬🇷", isEligible: true, requiresSupportingDocs: false },
  { code: "POL", name: "Poland", flag: "🇵🇱", isEligible: true, requiresSupportingDocs: false },
  { code: "CZE", name: "Czech Republic", flag: "🇨🇿", isEligible: true, requiresSupportingDocs: false },
  { code: "HUN", name: "Hungary", flag: "🇭🇺", isEligible: true, requiresSupportingDocs: false },
  { code: "SVK", name: "Slovakia", flag: "🇸🇰", isEligible: true, requiresSupportingDocs: false },
  { code: "SVN", name: "Slovenia", flag: "🇸🇮", isEligible: true, requiresSupportingDocs: false },
  { code: "ROU", name: "Romania", flag: "🇷🇴", isEligible: true, requiresSupportingDocs: false },
  { code: "BGR", name: "Bulgaria", flag: "🇧🇬", isEligible: true, requiresSupportingDocs: false },
  { code: "ARG", name: "Argentina", flag: "🇦🇷", isEligible: true, requiresSupportingDocs: false },
  { code: "CHL", name: "Chile", flag: "🇨🇱", isEligible: true, requiresSupportingDocs: false },
  { code: "COL", name: "Colombia", flag: "🇨🇴", isEligible: true, requiresSupportingDocs: false },
  { code: "PER", name: "Peru", flag: "🇵🇪", isEligible: true, requiresSupportingDocs: false },
  { code: "URY", name: "Uruguay", flag: "🇺🇾", isEligible: true, requiresSupportingDocs: false },
  { code: "ECU", name: "Ecuador", flag: "🇪🇨", isEligible: true, requiresSupportingDocs: false },
  { code: "BOL", name: "Bolivia", flag: "🇧🇴", isEligible: true, requiresSupportingDocs: false },
  { code: "PRY", name: "Paraguay", flag: "🇵🇾", isEligible: true, requiresSupportingDocs: false },
  { code: "VEN", name: "Venezuela", flag: "🇻🇪", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "NZL", name: "New Zealand", flag: "🇳🇿", isEligible: true, requiresSupportingDocs: false },
  { code: "UKR", name: "Ukraine", flag: "🇺🇦", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "BLR", name: "Belarus", flag: "🇧🇾", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "KAZ", name: "Kazakhstan", flag: "🇰🇿", isEligible: true, requiresSupportingDocs: false },
  { code: "UZB", name: "Uzbekistan", flag: "🇺🇿", isEligible: true, requiresSupportingDocs: false },
  { code: "TKM", name: "Turkmenistan", flag: "🇹🇲", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "KGZ", name: "Kyrgyzstan", flag: "🇰🇬", isEligible: true, requiresSupportingDocs: false },
  { code: "TJK", name: "Tajikistan", flag: "🇹🇯", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "MNG", name: "Mongolia", flag: "🇲🇳", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "JOR", name: "Jordan", flag: "🇯🇴", isEligible: true, requiresSupportingDocs: false },
  { code: "LBN", name: "Lebanon", flag: "🇱🇧", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "ISR", name: "Israel", flag: "🇮🇱", isEligible: true, requiresSupportingDocs: false },
  { code: "MAR", name: "Morocco", flag: "🇲🇦", isEligible: true, requiresSupportingDocs: false },
  { code: "TUN", name: "Tunisia", flag: "🇹🇳", isEligible: true, requiresSupportingDocs: false },
  { code: "ETH", name: "Ethiopia", flag: "🇪🇹", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "KEN", name: "Kenya", flag: "🇰🇪", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "GHA", name: "Ghana", flag: "🇬🇭", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "CIV", name: "Ivory Coast", flag: "🇨🇮", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "CMR", name: "Cameroon", flag: "🇨🇲", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "UGA", name: "Uganda", flag: "🇺🇬", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "TZA", name: "Tanzania", flag: "🇹🇿", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "RWA", name: "Rwanda", flag: "🇷🇼", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "ZWE", name: "Zimbabwe", flag: "🇿🇼", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "ZMB", name: "Zambia", flag: "🇿🇲", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "BWA", name: "Botswana", flag: "🇧🇼", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "AGO", name: "Angola", flag: "🇦🇴", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "MDG", name: "Madagascar", flag: "🇲🇬", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "MOZ", name: "Mozambique", flag: "🇲🇿", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "MWI", name: "Malawi", flag: "🇲🇼", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "SWZ", name: "Eswatini", flag: "🇸🇿", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "LSO", name: "Lesotho", flag: "🇱🇸", isEligible: true, requiresSupportingDocs: true, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  
  // Major countries that are visa-free (not e-visa eligible)
  { code: "USA", name: "United States", flag: "🇺🇸", isEligible: false, requiresSupportingDocs: false },
  { code: "GBR", name: "United Kingdom", flag: "🇬🇧", isEligible: false, requiresSupportingDocs: false },
  { code: "DEU", name: "Germany", flag: "🇩🇪", isEligible: false, requiresSupportingDocs: false },
  { code: "FRA", name: "France", flag: "🇫🇷", isEligible: false, requiresSupportingDocs: false },
  { code: "JPN", name: "Japan", flag: "🇯🇵", isEligible: false, requiresSupportingDocs: false },
  { code: "RUS", name: "Russian Federation", flag: "🇷🇺", isEligible: false, requiresSupportingDocs: false },
  { code: "NGA", name: "Nigeria", flag: "🇳🇬", isEligible: false, requiresSupportingDocs: false },
  { code: "SYR", name: "Syria", flag: "🇸🇾", isEligible: false, requiresSupportingDocs: false },
];

export const DOCUMENT_TYPES = [
  { value: "hotel", label: "Hotel Reservation" },
  { value: "flight", label: "Flight Reservation" },
  { value: "invitation", label: "Invitation Letter" },
  { value: "financial", label: "Financial Statement" },
  { value: "insurance", label: "Travel Insurance" },
];

export const PROCESSING_TYPES = [
  { value: "standard", label: "Standard Processing (5-7 days)", price: 0 },
  { value: "fast", label: "Fast Processing (1-3 days)", price: 50 },
  { value: "express", label: "Express Processing (24 hours)", price: 150 },
  { value: "urgent", label: "Urgent Processing (4 hours)", price: 270 },
];
