export interface CountryInfo {
  code: string;
  name: string;
  flag: string;
  scenario: 1 | 2 | 3 | 4; // 1: E-visa no docs, 2: E-visa with docs, 3: Visa-free + insurance, 4: Not eligible
  supportedDocumentTypes?: string[];
}

export const COUNTRIES: CountryInfo[] = [
  // Scenario 1: E-visa eligible + NO supporting document required (29 countries)
  { code: "BHS", name: "Bahamas", flag: "🇧🇸", scenario: 1 },
  { code: "BMU", name: "Bermuda", flag: "🇧🇲", scenario: 1 },
  { code: "ATG", name: "Antigua and Barbuda", flag: "🇦🇬", scenario: 1 },
  { code: "AUS", name: "Australia", flag: "🇦🇺", scenario: 1 },
  { code: "BRB", name: "Barbados", flag: "🇧🇧", scenario: 1 },
  { code: "CHN", name: "China", flag: "🇨🇳", scenario: 1 },
  { code: "TLS", name: "East Timor", flag: "🇹🇱", scenario: 1 },
  { code: "DOM", name: "Dominican Republic", flag: "🇩🇴", scenario: 1 },
  { code: "ARM", name: "Armenia", flag: "🇦🇲", scenario: 1 },
  { code: "FJI", name: "Fiji", flag: "🇫🇯", scenario: 1 },
  { code: "EST", name: "Estonia", flag: "🇪🇪", scenario: 1 },
  { code: "GRD", name: "Grenada", flag: "🇬🇩", scenario: 1 },
  { code: "ZAF", name: "South Africa", flag: "🇿🇦", scenario: 1 },
  { code: "CYP", name: "Cyprus", flag: "🇨🇾", scenario: 1 },
  { code: "HRV", name: "Croatia", flag: "🇭🇷", scenario: 1 },
  { code: "HKG", name: "Hong Kong", flag: "🇭🇰", scenario: 1 },
  { code: "JAM", name: "Jamaica", flag: "🇯🇲", scenario: 1 },
  { code: "LVA", name: "Latvia", flag: "🇱🇻", scenario: 1 },
  { code: "LTU", name: "Lithuania", flag: "🇱🇹", scenario: 1 },
  { code: "MDV", name: "Maldives", flag: "🇲🇻", scenario: 1 },
  { code: "MUS", name: "Mauritius", flag: "🇲🇺", scenario: 1 },
  { code: "MEX", name: "Mexico", flag: "🇲🇽", scenario: 1 },
  { code: "EGY", name: "Egypt", flag: "🇪🇬", scenario: 1 }, // Age-based: Under 15 or over 45
  { code: "NAM", name: "Namibia", flag: "🇳🇦", scenario: 1 },
  { code: "LCA", name: "Saint Lucia", flag: "🇱🇨", scenario: 1 },
  { code: "VCT", name: "Saint Vincent and the Grenadines", flag: "🇻🇨", scenario: 1 },
  { code: "SUR", name: "Suriname", flag: "🇸🇷", scenario: 1 },
  { code: "TWN", name: "Taiwan", flag: "🇹🇼", scenario: 1 },
  { code: "VNM", name: "Vietnam", flag: "🇻🇳", scenario: 1 },

  // Scenario 2: E-visa eligible + supporting document required (20 countries)
  { code: "AFG", name: "Afghanistan", flag: "🇦🇫", scenario: 2, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "BGD", name: "Bangladesh", flag: "🇧🇩", scenario: 2, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "DZA", name: "Algeria", flag: "🇩🇿", scenario: 2, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "GNQ", name: "Equatorial Guinea", flag: "🇬🇶", scenario: 2, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "PHL", name: "Philippines", flag: "🇵🇭", scenario: 2, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "PSE", name: "Palestine", flag: "🇵🇸", scenario: 2, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "HTI", name: "Haiti", flag: "🇭🇹", scenario: 2, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "IND", name: "India", flag: "🇮🇳", scenario: 2, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "IRQ", name: "Iraq", flag: "🇮🇶", scenario: 2, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "KHM", name: "Cambodia", flag: "🇰🇭", scenario: 2, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "LBY", name: "Libya", flag: "🇱🇾", scenario: 2, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "EGY", name: "Egypt", flag: "🇪🇬", scenario: 2, supportedDocumentTypes: ["hotel", "flight", "financial"] }, // Age-based: 15-45 years
  { code: "NPL", name: "Nepal", flag: "🇳🇵", scenario: 2, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "PAK", name: "Pakistan", flag: "🇵🇰", scenario: 2, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "SEN", name: "Senegal", flag: "🇸🇳", scenario: 2, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "SLB", name: "Solomon Islands", flag: "🇸🇧", scenario: 2, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "LKA", name: "Sri Lanka", flag: "🇱🇰", scenario: 2, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "VUT", name: "Vanuatu", flag: "🇻🇺", scenario: 2, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "YEM", name: "Yemen", flag: "🇾🇪", scenario: 2, supportedDocumentTypes: ["hotel", "flight", "financial"] },
  { code: "CPV", name: "Cape Verde", flag: "🇨🇻", scenario: 2, supportedDocumentTypes: ["hotel", "flight", "financial"] },

  // Scenario 4: Not eligible for e-visa (104 countries)
  { code: "AGO", name: "Angola", flag: "🇦🇴", scenario: 4 },
  { code: "AIA", name: "Anguilla", flag: "🇦🇮", scenario: 4 },
  { code: "ABW", name: "Aruba", flag: "🇦🇼", scenario: 4 },
  { code: "BEN", name: "Benin", flag: "🇧🇯", scenario: 4 },
  { code: "BWA", name: "Botswana", flag: "🇧🇼", scenario: 4 },
  { code: "BFA", name: "Burkina Faso", flag: "🇧🇫", scenario: 4 },
  { code: "BDI", name: "Burundi", flag: "🇧🇮", scenario: 4 },
  { code: "DJI", name: "Djibouti", flag: "🇩🇯", scenario: 4 },
  { code: "COK", name: "Cook Islands", flag: "🇨🇰", scenario: 4 },
  { code: "TCD", name: "Chad", flag: "🇹🇩", scenario: 4 },
  { code: "DMA", name: "Dominica", flag: "🇩🇲", scenario: 4 },
  { code: "ERI", name: "Eritrea", flag: "🇪🇷", scenario: 4 },
  { code: "ETH", name: "Ethiopia", flag: "🇪🇹", scenario: 4 },
  { code: "FRO", name: "Faroe Islands", flag: "🇫🇴", scenario: 4 },
  { code: "CIV", name: "Ivory Coast", flag: "🇨🇮", scenario: 4 },
  { code: "GAB", name: "Gabon", flag: "🇬🇦", scenario: 4 },
  { code: "GMB", name: "Gambia", flag: "🇬🇲", scenario: 4 },
  { code: "GHA", name: "Ghana", flag: "🇬🇭", scenario: 4 },
  { code: "GIN", name: "Guinea", flag: "🇬🇳", scenario: 4 },
  { code: "GNB", name: "Guinea-Bissau", flag: "🇬🇼", scenario: 4 },
  { code: "GRL", name: "Greenland", flag: "🇬🇱", scenario: 4 },
  { code: "GLP", name: "Guadeloupe", flag: "🇬🇵", scenario: 4 },
  { code: "GUM", name: "Guam", flag: "🇬🇺", scenario: 4 },
  { code: "GUY", name: "Guyana", flag: "🇬🇾", scenario: 4 },
  { code: "SSD", name: "South Sudan", flag: "🇸🇸", scenario: 4 },
  { code: "CMR", name: "Cameroon", flag: "🇨🇲", scenario: 4 },
  { code: "CYM", name: "Cayman Islands", flag: "🇰🇾", scenario: 4 },
  { code: "KEN", name: "Kenya", flag: "🇰🇪", scenario: 4 },
  { code: "KIR", name: "Kiribati", flag: "🇰🇮", scenario: 4 },
  { code: "COM", name: "Comoros", flag: "🇰🇲", scenario: 4 },
  { code: "COG", name: "Republic of the Congo", flag: "🇨🇬", scenario: 4 },
  { code: "COD", name: "Democratic Republic of the Congo", flag: "🇨🇩", scenario: 4 },
  { code: "PRK", name: "North Korea", flag: "🇰🇵", scenario: 4 },
  { code: "CUB", name: "Cuba", flag: "🇨🇺", scenario: 4 },
  { code: "LAO", name: "Laos", flag: "🇱🇦", scenario: 4 },
  { code: "LSO", name: "Lesotho", flag: "🇱🇸", scenario: 4 },
  { code: "LBR", name: "Liberia", flag: "🇱🇷", scenario: 4 },
  { code: "MDG", name: "Madagascar", flag: "🇲🇬", scenario: 4 },
  { code: "MWI", name: "Malawi", flag: "🇲🇼", scenario: 4 },
  { code: "MLI", name: "Mali", flag: "🇲🇱", scenario: 4 },
  { code: "MHL", name: "Marshall Islands", flag: "🇲🇭", scenario: 4 },
  { code: "MTQ", name: "Martinique", flag: "🇲🇶", scenario: 4 },
  { code: "MYT", name: "Mayotte", flag: "🇾🇹", scenario: 4 },
  { code: "FSM", name: "Micronesia", flag: "🇫🇲", scenario: 4 },
  { code: "MRT", name: "Mauritania", flag: "🇲🇷", scenario: 4 },
  { code: "MOZ", name: "Mozambique", flag: "🇲🇿", scenario: 4 },
  { code: "MMR", name: "Myanmar", flag: "🇲🇲", scenario: 4 },
  { code: "NRU", name: "Nauru", flag: "🇳🇷", scenario: 4 },
  { code: "NER", name: "Niger", flag: "🇳🇪", scenario: 4 },
  { code: "NGA", name: "Nigeria", flag: "🇳🇬", scenario: 4 },
  { code: "NFK", name: "Norfolk Island", flag: "🇳🇫", scenario: 4 },
  { code: "CAF", name: "Central African Republic", flag: "🇨🇫", scenario: 4 },
  { code: "PLW", name: "Palau", flag: "🇵🇼", scenario: 4 },
  { code: "PNG", name: "Papua New Guinea", flag: "🇵🇬", scenario: 4 },
  { code: "PRI", name: "Puerto Rico", flag: "🇵🇷", scenario: 4 },
  { code: "REU", name: "Reunion", flag: "🇷🇪", scenario: 4 },
  { code: "RWA", name: "Rwanda", flag: "🇷🇼", scenario: 4 },
  { code: "WSM", name: "Samoa", flag: "🇼🇸", scenario: 4 },
  { code: "STP", name: "Sao Tome and Principe", flag: "🇸🇹", scenario: 4 },
  { code: "KNA", name: "Saint Kitts and Nevis", flag: "🇰🇳", scenario: 4 },
  { code: "SLE", name: "Sierra Leone", flag: "🇸🇱", scenario: 4 },
  { code: "SOM", name: "Somalia", flag: "🇸🇴", scenario: 4 },
  { code: "SDN", name: "Sudan", flag: "🇸🇩", scenario: 4 },
  { code: "SYR", name: "Syria", flag: "🇸🇾", scenario: 4 },
  { code: "SWZ", name: "Eswatini", flag: "🇸🇿", scenario: 4 },
  { code: "TJK", name: "Tajikistan", flag: "🇹🇯", scenario: 4 },
  { code: "TZA", name: "Tanzania", flag: "🇹🇿", scenario: 4 },
  { code: "TGO", name: "Togo", flag: "🇹🇬", scenario: 4 },
  { code: "TON", name: "Tonga", flag: "🇹🇴", scenario: 4 },
  { code: "TCA", name: "Turks and Caicos Islands", flag: "🇹🇨", scenario: 4 },
  { code: "TUV", name: "Tuvalu", flag: "🇹🇻", scenario: 4 },
  { code: "TKM", name: "Turkmenistan", flag: "🇹🇲", scenario: 4 },
  { code: "UGA", name: "Uganda", flag: "🇺🇬", scenario: 4 },
  { code: "NCL", name: "New Caledonia", flag: "🇳🇨", scenario: 4 },
  { code: "ZWE", name: "Zimbabwe", flag: "🇿🇼", scenario: 4 },

  // Scenario 3: E-visa exempt + travel insurance mandatory (all other countries)
  { code: "USA", name: "United States", flag: "🇺🇸", scenario: 3 },
  { code: "GBR", name: "United Kingdom", flag: "🇬🇧", scenario: 3 },
  { code: "DEU", name: "Germany", flag: "🇩🇪", scenario: 3 },
  { code: "FRA", name: "France", flag: "🇫🇷", scenario: 3 },
  { code: "JPN", name: "Japan", flag: "🇯🇵", scenario: 3 },
  { code: "ITA", name: "Italy", flag: "🇮🇹", scenario: 3 },
  { code: "ESP", name: "Spain", flag: "🇪🇸", scenario: 3 },
  { code: "NLD", name: "Netherlands", flag: "🇳🇱", scenario: 3 },
  { code: "BRA", name: "Brazil", flag: "🇧🇷", scenario: 3 },
  { code: "KWT", name: "Kuwait", flag: "🇰🇼", scenario: 3 },
  { code: "OMN", name: "Oman", flag: "🇴🇲", scenario: 3 },
  { code: "QAT", name: "Qatar", flag: "🇶🇦", scenario: 3 },
  { code: "SAU", name: "Saudi Arabia", flag: "🇸🇦", scenario: 3 },
  { code: "ARE", name: "United Arab Emirates", flag: "🇦🇪", scenario: 3 },
  { code: "BHR", name: "Bahrain", flag: "🇧🇭", scenario: 3 },
  { code: "THA", name: "Thailand", flag: "🇹🇭", scenario: 3 },
  { code: "SGP", name: "Singapore", flag: "🇸🇬", scenario: 3 },
  { code: "MYS", name: "Malaysia", flag: "🇲🇾", scenario: 3 },
  { code: "IDN", name: "Indonesia", flag: "🇮🇩", scenario: 3 },
  { code: "KOR", name: "South Korea", flag: "🇰🇷", scenario: 3 },
  { code: "NOR", name: "Norway", flag: "🇳🇴", scenario: 3 },
  { code: "SWE", name: "Sweden", flag: "🇸🇪", scenario: 3 },
  { code: "DNK", name: "Denmark", flag: "🇩🇰", scenario: 3 },
  { code: "FIN", name: "Finland", flag: "🇫🇮", scenario: 3 },
  { code: "BEL", name: "Belgium", flag: "🇧🇪", scenario: 3 },
  { code: "AUT", name: "Austria", flag: "🇦🇹", scenario: 3 },
  { code: "CHE", name: "Switzerland", flag: "🇨🇭", scenario: 3 },
  { code: "PRT", name: "Portugal", flag: "🇵🇹", scenario: 3 },
  { code: "GRC", name: "Greece", flag: "🇬🇷", scenario: 3 },
  { code: "POL", name: "Poland", flag: "🇵🇱", scenario: 3 },
  { code: "CZE", name: "Czech Republic", flag: "🇨🇿", scenario: 3 },
  { code: "HUN", name: "Hungary", flag: "🇭🇺", scenario: 3 },
  { code: "SVK", name: "Slovakia", flag: "🇸🇰", scenario: 3 },
  { code: "SVN", name: "Slovenia", flag: "🇸🇮", scenario: 3 },
  { code: "ROU", name: "Romania", flag: "🇷🇴", scenario: 3 },
  { code: "BGR", name: "Bulgaria", flag: "🇧🇬", scenario: 3 },
  { code: "ARG", name: "Argentina", flag: "🇦🇷", scenario: 3 },
  { code: "CHL", name: "Chile", flag: "🇨🇱", scenario: 3 },
  { code: "COL", name: "Colombia", flag: "🇨🇴", scenario: 3 },
  { code: "PER", name: "Peru", flag: "🇵🇪", scenario: 3 },
  { code: "URY", name: "Uruguay", flag: "🇺🇾", scenario: 3 },
  { code: "ECU", name: "Ecuador", flag: "🇪🇨", scenario: 3 },
  { code: "BOL", name: "Bolivia", flag: "🇧🇴", scenario: 3 },
  { code: "PRY", name: "Paraguay", flag: "🇵🇾", scenario: 3 },
  { code: "NZL", name: "New Zealand", flag: "🇳🇿", scenario: 3 },
  { code: "UKR", name: "Ukraine", flag: "🇺🇦", scenario: 3 },
  { code: "KAZ", name: "Kazakhstan", flag: "🇰🇿", scenario: 3 },
  { code: "UZB", name: "Uzbekistan", flag: "🇺🇿", scenario: 3 },
  { code: "KGZ", name: "Kyrgyzstan", flag: "🇰🇬", scenario: 3 },
  { code: "MNG", name: "Mongolia", flag: "🇲🇳", scenario: 3 },
  { code: "JOR", name: "Jordan", flag: "🇯🇴", scenario: 3 },
  { code: "LBN", name: "Lebanon", flag: "🇱🇧", scenario: 3 },
  { code: "ISR", name: "Israel", flag: "🇮🇱", scenario: 3 },
  { code: "MAR", name: "Morocco", flag: "🇲🇦", scenario: 3 },
  { code: "TUN", name: "Tunisia", flag: "🇹🇳", scenario: 3 },
  { code: "ZMB", name: "Zambia", flag: "🇿🇲", scenario: 3 },
  { code: "VEN", name: "Venezuela", flag: "🇻🇪", scenario: 3 },
  { code: "RUS", name: "Russia", flag: "🇷🇺", scenario: 3 },
  { code: "CAN", name: "Canada", flag: "🇨🇦", scenario: 3 },
  { code: "IRN", name: "Iran", flag: "🇮🇷", scenario: 3 },
  { code: "GEO", name: "Georgia", flag: "🇬🇪", scenario: 3 },
  { code: "AZE", name: "Azerbaijan", flag: "🇦🇿", scenario: 3 },
  { code: "BLR", name: "Belarus", flag: "🇧🇾", scenario: 3 },
  { code: "MDA", name: "Moldova", flag: "🇲🇩", scenario: 3 },
  { code: "LUX", name: "Luxembourg", flag: "🇱🇺", scenario: 3 },
  { code: "ISL", name: "Iceland", flag: "🇮🇸", scenario: 3 },
  { code: "IRL", name: "Ireland", flag: "🇮🇪", scenario: 3 },
  { code: "LIE", name: "Liechtenstein", flag: "🇱🇮", scenario: 3 },
  { code: "MCO", name: "Monaco", flag: "🇲🇨", scenario: 3 },
  { code: "MTU", name: "Malta", flag: "🇲🇹", scenario: 3 },
  { code: "SMR", name: "San Marino", flag: "🇸🇲", scenario: 3 },
  { code: "VAT", name: "Vatican City", flag: "🇻🇦", scenario: 3 },
  { code: "AND", name: "Andorra", flag: "🇦🇩", scenario: 3 },
  { code: "ALB", name: "Albania", flag: "🇦🇱", scenario: 3 },
  { code: "BIH", name: "Bosnia and Herzegovina", flag: "🇧🇦", scenario: 3 },
  { code: "MKD", name: "North Macedonia", flag: "🇲🇰", scenario: 3 },
  { code: "MNE", name: "Montenegro", flag: "🇲🇪", scenario: 3 },
  { code: "SRB", name: "Serbia", flag: "🇷🇸", scenario: 3 },
  { code: "XKX", name: "Kosovo", flag: "🇽🇰", scenario: 3 },
];

export const DOCUMENT_TYPES = [
  { value: "hotel", label: "Hotel Reservation" },
  { value: "flight", label: "Flight Reservation" },
  { value: "invitation", label: "Invitation Letter" },
  { value: "financial", label: "Financial Statement" },
  { value: "insurance", label: "Travel Insurance" },
];